apiVersion: v1
kind: Service
metadata:
  name: {{ include "pokedex.fullname" . }}-frontend
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontendService.type }}
  ports:
    - port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendService.port }}
      protocol: TCP
      name: http
  selector:
    app: pokedex-frontend