
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-java-app
spec:
  description: Use maven wrapper to build Java app
  workspaces:
  - name: source
  steps:
  - name: build-app
    image: registry.access.redhat.com/ubi8/openjdk-17:1.14
    script: | 
      #!/usr/bin/env sh
      cd $(workspaces.source.path)/backend
      ./mvnw package -DskipTests