apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec: 
  description: |
    This pipeline clones a git repo, builds the backend Java app, builds the backend image, and pushes that image to a Quay repo
  params:
  - name: repo-url
    type: string
    description: git repo URL to clone from
  - name: IMAGE
    type: string
    description: image to be built from the code
  - name: CONTEXT
    type: string
    description: path to directory to use as context (default is .)
  - name: DOCKERFILE
    type: string
    description: path to Dockerfile (default is ./Dockerfile)
  workspaces: 
  - name: shared-data
    description: contains the cloned files so they can be read by the next task
  - name: docker-credentials
    description: quay robo creds
  tasks:
  - name: fetch-source
    taskRef: 
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params: 
    - name: url
      value: $(params.repo-url)
  - name: build-java-app
    runAfter:
    - fetch-source
    taskRef:
      name: build-java-app
    workspaces:
    - name: source
      workspace: shared-data
  - name: build-image
    runAfter:
    - build-java-app
    taskRef: 
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    - name: CONTEXT
      value: $(params.CONTEXT)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE)
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: docker-credentials