apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokedex-frontend
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: pokedex-frontend
    spec:
      containers:
        - name: pokedex-frontend
          image: "quay.io/bhouse/quarkus/pokedex-frontend:1.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
