version: '3.9'

services:
  quarkus:
    build: 
      context: ./backend/src/main/docker
      dockerfile: Dockerfile.jvm
    command: ["quarkus dev"]
    ports:
      - "8080:8080"
  frontend:
    build: 
      context: ./frontend
    command: ["npm", "run", "start:dev"]
    ports:
      - "3000:3000"