version: '3'

services:
  quarkus:
    build: ./backend
    command: ["quarkus dev"]
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    command: ["npm", "run", "start:dev"]
    ports:
      - "3000:3000"