apiVersion: v1
kind: Service
metadata:
  name: {{ include "pokedex.fullname" . }}-backend
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backendService.type }}
  ports:
    - port: {{ .Values.backendService.port }}
      targetPort: {{ .Values.backendService.port }}
      protocol: TCP
      name: http
  selector:
    app: pokedex-backend
